
# R CODE FOR IMPORTING, MANIPULATING, AND ANALYZING THE DATASETS USED IN ESPIN ET AL: GEOGRAPHY OF EDITORIAL BOARDS

# R & Package versions:
# R version = 3.3.1
# vegan = 2.4.2
# tidyverse = 1.0
# MuMIn = 1.15.6
# nlme = 3.1.128

##############################################################
##############################################################
#
# GETTING STARTED
#
##############################################################
##############################################################

# Load required libraries
library(tidyverse)
library(vegan)
library(nlme)
library(MuMIn)


# Clear the environment 
rm(list=ls())


##############################################################
##############################################################
#
# DATA UPLOAD & STANDARDIZATION
#
##############################################################
##############################################################

Cho<-read.csv("./Data/Drayd.Cho.v2.csv", dec=".", header = TRUE, sep = ",", check.names=FALSE )
Espin<-read.csv("./Data/Drayd.Espin.v1.csv", dec=".", header = TRUE, sep = ",", check.names=FALSE )

#Bind the datasets together
ALLDATA<-bind_rows(Drayd_Cho_v2,Drayd_Espin_v1)

#Add the ISO Code for the country in which editor's are based 
source("Country.Codes.R")
ALLDATA<-Country.Codes(ALLDATA)
levels(ALLDATA$geo.code)

# Add the geographic region and national income category in whihc editors are based
source("AddIncomeRegion.R")
ALLDATA<-AddIncomeRegion(ALLDATA)


##############################################################
##############################################################
#
# STANDARDIZE DATASETS AND SELECT TIME FRAME AND 
# EDITOR CATEGORIES FOR ANALYSIS
#
##############################################################
##############################################################


# DEFINE THE TEMPORAL RANGE OF THE ANALYSES (the datasets include data for years beyond what was used in Espin et al.)
FirstYear=1985
LastYear=2014

# The analyses are conducted on a new dataframe "AnalysisData" spanning onlly the years of interest. 
# This is done to allow one to analyze over different temporal windows without having to reload, rebind, and restandardize the datasets
AnalysisData<-ALLDATA[ALLDATA$YEAR>=FirstYear & ALLDATA$YEAR<=LastYear,]

# Choose the classes of editor of interest: For Espin et al analyses were done with EIC, AE, SE, and Special Editors
AnalysisData <- AnalysisData[AnalysisData$CATEGORY %in% c('EIC', 'AE', 'SE', 'SPECIAL'),]

# delete unused columns 
AnalysisData<-AnalysisData %>% select(-NOTES,-GENDER, -VOLUME, -ISSUE, -TITLE)

# Convert editor ID to type: factor
AnalysisData$editor_id<-as.factor(AnalysisData$editor_id)

# Convert YEAR to type: numeric
AnalysisData$YEAR<-as.numeric(AnalysisData$YEAR)

# Espin et al considered French Guiana HIGH INCOME OECD income category and LATIN AMERICA/CARRIBBEAN region
# This reflects that scientists in GUF have access to more financial resources because part of France BUT
# have insights into local conditions because of where based.
AnalysisData$REGION[AnalysisData$geo.code == "GUF"]  <- "Latin America & Caribbean"
AnalysisData$INCOME_LEVEL[AnalysisData$geo.code == "GUF"]  <- "High income: OECD"



##############################################################
##############################################################
#
# ANALYSES
#
##############################################################

##############################################################
##############################################################
# Total Number of (Unique) Editors in the Community
eds<-AnalysisData %>% summarise(n_distinct(editor_id))
eds
##############################################################

##############################################################
# Total number of countries represented by Editors 
countries<-AnalysisData %>% summarise(n_distinct(geo.code))
countries
##############################################################

##############################################################
# Cumulative Geographic Richness: Cumulative Number of countries represented through year X
# Used in Figure 1A
# Use Rarefaction curves generated by vegan then convett back to tibble
editorAcum<-AnalysisData %>% group_by(YEAR, geo.code) %>% summarize(yr_tot = n_distinct(geo.code))
editorAcum<-spread(editorAcum, geo.code,yr_tot) 
editorAcum[is.na(editorAcum)] <- 0
editorAcum<-ungroup(editorAcum)
editorAcum<-select(editorAcum,-YEAR)
editorAcum<-specaccum(editorAcum, "collector")
editorAcum<-as_tibble(editorAcum$richness)
names(editorAcum)[1] <- "CumulativeRichness"
editorAcum$YEAR<-seq(1985,2014,1)
editorAcum
##############################################################

##############################################################
# Annual Geographic Richness: Number of countries represented in year X 
# Used in Figure 1A
GEOperYR<-AnalysisData %>% group_by(YEAR) %>% summarize(AnnualRichness = n_distinct(geo.code)) 
GEOperYR
##############################################################


##############################################################
# Total Number of Editors (all jrnls pooled)  vs. Year
# Used in Figure 1B
EdsPerYr<-AnalysisData %>% group_by(YEAR) %>% summarize(TotalEditors = n_distinct(editor_id))
EdsPerYr
##############################################################

##############################################################
# Geographic Diversity (all journals pooled) 
# Geographic Evenness (all journals pooled) 
# Used in Figure 1C and 1D
DivDataPooled<-AnalysisData %>% group_by(YEAR, geo.code) %>% summarize(Total = n_distinct(editor_id)) 
# DivDataPooled<-as.data.frame(EdsPerCountryPerJrnlPerYr.LONG)
DivDataPooled<-DivDataPooled %>% group_by(YEAR, geo.code) %>% summarise(Total_Eds=sum(Total))
DivDataPooled<-spread(DivDataPooled, geo.code, Total_Eds) 
DivDataPooled[is.na(DivDataPooled)] <- 0
DivDataPooled<-ungroup(DivDataPooled)
# 4: Geo Diverisity using Simpson's Inverse
IsimpDivTable <- diversity((DivDataPooled %>% select(-YEAR)), index="invsimpson") #Need to strip away the journal and year columns for vegan to do the analysis
# Table DIVERSITY with Results and Journals
IsimpDivTable <- data.frame(IsimpDivTable)
IsimpDivTable$YEAR <-DivDataPooled$YEAR #Add year as a column
IsimpDivTable<-rename(IsimpDivTable, InvSimpson=IsimpDivTable) #rename the columns
IsimpDivTable <- IsimpDivTable[c("YEAR","InvSimpson")] #reorder the columns
IsimpDivTable<-as_tibble(IsimpDivTable)

# 4: Geographic Evenness (all journals pooled) 
IsimpDivTable<-full_join(GEOperYR,IsimpDivTable, by="YEAR")
IsimpDivTable<-mutate(IsimpDivTable, Geo.Evenness = InvSimpson/AnnualRichness)

IsimpDivTable
##############################################################


##############################################################
# Number and Pcnt of Editors from Each Country (all journals and years pooled)
# Used for Fig 2A
Editor.Geo<-AnalysisData %>%  group_by(geo.code) %>% 
  summarize(N_editors = n_distinct(editor_id)) %>% 
  mutate(Pcnt_editors= (N_editors/sum(N_editors)*100)) %>% 
  arrange(desc(Pcnt_editors))
Editor.Geo
##############################################################


##############################################################
# Number / Percentage of Editors from Different Regions (all journals pooled)
# Used for Fig. 2b
RegionPlot<-AnalysisData %>% select(YEAR,editor_id,REGION,CATEGORY) %>% group_by(editor_id) 
RegionPlot<-distinct(RegionPlot, editor_id,YEAR, .keep_all = TRUE)
RegionPlot<-RegionPlot %>% group_by(YEAR,REGION) %>% count(YEAR,REGION)
RegionPlot<-RegionPlot %>% group_by(YEAR) %>% mutate(yr_tot=sum(n)) %>% mutate(Percent=n/yr_tot*100) 
RegionPlot
#RegionPlot %>%  group_by(YEAR) %>% mutate(sum=sum(Percent)) checks that add up to 100%
##############################################################

##############################################################
# Number / Percentage of Editors from Different Income Levels, all journals pooled 
# USed for Fig. 2c
IncomePlot<-AnalysisData %>% select(YEAR,editor_id,INCOME_LEVEL,CATEGORY) %>% group_by(editor_id) 
IncomePlot<-distinct(IncomePlot, editor_id,YEAR, .keep_all = TRUE)
IncomePlot<-IncomePlot %>% group_by(YEAR,INCOME_LEVEL) %>% count(YEAR,INCOME_LEVEL)
IncomePlot<-IncomePlot %>% group_by(YEAR) %>% mutate(yr_tot=sum(n)) %>% mutate(Percent=n/yr_tot*100) 
IncomePlot
#IncomePlot %>%  group_by(YEAR) %>% mutate(sum=sum(Percent)) checks that add up to 100%
##############################################################



######################################################
######################################################
#
# FIGURES AND TABLES
#
######################################################
######################################################


# Convert Journal Codes to Journal Names (for figures and analyses)
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="BITR"] <- "Biotropica"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="PLANTECOL"] <- "Plant Ecology"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="AGRONOMY"] <- "Agronomy Journal"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="AJB"] <- "American J. Botany"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="CONBIO"] <- "Conservation Biology"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="ECOLOGY"] <- "Ecology"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="BIOCON"] <- "Biological Conservation"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="JECOL"] <- "J. of Ecology"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="JTE"] <- "J. Tropical Ecology"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="AMNAT"] <- "American Naturalist"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="JBIOG"] <- "J. Biogeography"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="ECOGRAPHY"] <- "Ecography"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="EVOL"] <- "Evolution"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="FEM"] <- "Forest Ecology & Managment"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="FUNECOL"] <- "Functional Ecology"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="LECO"] <- "Landscape Ecology"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="JZOOL"] <- "J. Zoology"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="JAPE"] <- "J. Applied Ecology"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="JANE"] <- "J. Animal Ecology"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="NEWPHYT"] <- "New Phytologist"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="OECOL"] <- "Oecologia"
AnalysisData$JOURNAL[AnalysisData$JOURNAL=="OIKOS"] <- "Oikos"

AnalysisData$JOURNAL<-as.factor(AnalysisData$JOURNAL)
#############################################################


##############################################################
# TABLE 1
##############################################################

# Total Editors in each National Income Class
EdsByIncome<-AnalysisData %>% select(INCOME_LEVEL,editor_id)
EdsByIncome<-distinct(EdsByIncome) %>% group_by(INCOME_LEVEL) %>% summarize(Total = n_distinct(editor_id))
sum(EdsByIncome$Total)

# Total by Region
EdsByRegion<-AnalysisData %>% group_by(REGION) %>% summarize(Total = n_distinct(editor_id))
sum(EdsByRegion$Total)

EdsByRegion<-AnalysisData %>% select(REGION,editor_id)
EdsByRegion<-distinct(EdsByRegion) %>% group_by(REGION) %>% summarize(Total = n_distinct(editor_id))

#Number / Percentage of Editor Types from Different Regions, all years pooled
EdCat.region<-AnalysisData %>% group_by(CATEGORY, REGION)  %>%  summarize(N=n_distinct(editor_id))  %>% mutate(Pcnt=N/sum(N)*100) 
EdCat.region$Pcnt<-round(EdCat.region$Pcnt, digits=2)
sumsI<-EdCat.region %>% group_by(CATEGORY) %>% summarize(sum=sum(N))
EdCat.region<-EdCat.region %>% select(-N) %>% spread(CATEGORY, Pcnt)
EdCat.region[is.na(EdCat.region)] <- 0
EdCat.region

# Number / Percentage of Editor Types from Different Income Levels, all years pooled 
EdCat.income<-AnalysisData %>% group_by(CATEGORY, INCOME_LEVEL)  %>%  summarize(N=n_distinct(editor_id))  %>% mutate(Pcnt=N/sum(N)*100) 
EdCat.income$Pcnt<-round(EdCat.income$Pcnt, digits=2)
sumsR<-EdCat.income %>% group_by(CATEGORY) %>% summarize(sum=sum(N))
EdCat.income<-EdCat.income %>% select(-N) %>% spread(CATEGORY, Pcnt)
EdCat.income[is.na(EdCat.income)] <- 0

EdsByIncome
EdsByRegion
EdCat.income
EdCat.region


##############################################################
# Fig. 1A: Cumulative Geo Richness
##############################################################

# PUT THE NECESSARY DATA IN ONE DATAFRAME 
jointGEOperYR<-GEOperYR
jointedAccDF<-editorAcum

jointGEOperYR<-rename(jointGEOperYR,Countries=AnnualRichness)
jointRichness<-full_join(jointGEOperYR, jointedAccDF, by = "YEAR")
jointRichness<-gather(jointRichness, "Richness","N", 2:3)
jointRichness[jointRichness=="Countries"]<-"Annual"
jointRichness[jointRichness=="CumulativeRichness"]<-"Cumulative"
rm(jointGEOperYR,jointedAccDF)

#plot cumulative and annual richness same plot
jointRichnessPlot<-ggplot(jointRichness, aes(x=YEAR, y=N, group = Richness, colour = Richness)) +
  geom_line(size=1) +
  scale_color_manual(values=c("blue", "red"))+
  geom_text(data = jointRichness[jointRichness$YEAR=="2012" & jointRichness$Richness=="Annual",], aes(label = Richness), hjust = 1, vjust = -1, size=5) +
  geom_text(data = jointRichness[jointRichness$YEAR=="2012" & jointRichness$Richness=="Cumulative",], aes(label = Richness), hjust = 1, vjust = -1, size=5) +
  #ylab("Number of Countries") +
  xlab("Year")+
  ggtitle('(A) Geographic Richness')+
  geom_point(color="black", shape=1)+
  # scale_y_continuous(breaks=seq(0, 1, 0.1))+
  scale_y_continuous(limits = c(25, 75))+
  scale_x_continuous(breaks=seq(1985, 2015, 5))

jointRichnessPlot<-jointRichnessPlot+theme_classic()+
  theme(axis.title.x=element_text(colour="black", size = 14, vjust=0),            #sets x axis title size, style, distance from axis #add , face = "bold" if you want bold
        #axis.title.y=element_text(colour="black", size = 14, vjust=2),            #sets y axis title size, style, distance from axis #add , face = "bold" if you want bold
        axis.title.y=element_blank(),
        axis.text=element_text(colour="black", size = 10),                              #sets size and style of labels on axes
        legend.title = element_blank(),   #Removes the Legend title
        legend.text = element_text(color="black", size=10),  
        # legend.position = c(0.9,0.8),
        legend.position = ("none"),
        legend.background = element_rect(colour = 'black', size = 0.5, linetype='solid'),
        plot.margin =unit(c(1,1.5,1,1), "cm")) #+  #plot margin - top, right, bottom, left
jointRichnessPlot


##############################################################
# Fig 1B: Total Number of Editors (all jrnls pooled)  vs. Year
##############################################################

plotTOTALEDSvYear<-ggplot(EdsPerYr, aes(x=YEAR, y=TotalEditors)) +
  #ylab("Number of Editors") +
  xlab("Year")+
  geom_line(size=1, color="blue")+
  ggtitle('(B) Number of Editors') + 
  geom_point(color="black", shape=1)+
  scale_y_continuous(breaks=seq(0, 1500, 150))+
  scale_x_continuous(breaks=seq(1985, 2015, 5))
plotTOTALEDSvYear<-plotTOTALEDSvYear+theme_classic()+
  theme(axis.title.x=element_text(colour="black", size = 14, vjust=0),            #sets x axis title size, style, distance from axis #add , face = "bold" if you want bold
        #axis.title.y=element_text(colour="black", size = 14, vjust=2),            #sets y axis title size, style, distance from axis #add , face = "bold" if you want bold
        axis.title.y=element_blank(),
        axis.text=element_text(colour="black", size = 10),                              #sets size and style of labels on axes
        legend.title = element_blank(),   #Removes the Legend title
        legend.text = element_text(color="black", size=10),  
        legend.position = c(0.9,0.8),
        legend.background = element_rect(colour = 'black', size = 0.5, linetype='solid'),
        plot.margin =unit(c(1,1.5,1,1), "cm")) #+  #plot margin - top, right, bottom, left
plotTOTALEDSvYear


##############################################################
# Plot 1C: COMMUNITY (POOLED JOURNALS) LEVEL DIVERSITY
##############################################################

plotPOOLEDsimpdiv<-ggplot(IsimpDivTable, aes(x=YEAR, y=InvSimpson)) +
  geom_line(size=1, color="blue") + # Use hollow circles
  #ylab("Geographic Diversity") +
  xlab("Year")+
  ggtitle('(C) Geographic Diversity')+
  geom_point(color="black", shape=1)+
  # scale_y_continuous(breaks=seq(2, 5.5, 0.5))+
  scale_y_continuous(limits=c(1,max(IsimpDivTable$AnnualRichness)))+
  scale_x_continuous(breaks=seq(1985, 2015, 5))
plotPOOLEDsimpdiv<-plotPOOLEDsimpdiv+theme_classic()+
  theme(axis.title.x=element_text(colour="black", size = 14, vjust=0),            #sets x axis title size, style, distance from axis #add , face = "bold" if you want bold
        #axis.title.y=element_text(colour="black", size = 14, vjust=2),            #sets y axis title size, style, distance from axis #add , face = "bold" if you want bold
        axis.title.y=element_blank(),
        axis.text=element_text(colour="black", size = 10),                              #sets size and style of labels on axes
        legend.title = element_blank(),   #Removes the Legend title
        legend.text = element_text(color="black", size=10),  
        legend.position = c(0.9,0.8),
        legend.background = element_rect(colour = 'black', size = 0.5, linetype='solid'),
        plot.margin =unit(c(1,1.5,1,1), "cm")) #+  #plot margin - top, right, bottom, left
plotPOOLEDsimpdiv


##############################################################
# Plot 1D: COMMUNITY (POOLED JOURNALS) LEVEL EVENNESS
##############################################################

plotPOOLEDevenness<-ggplot(IsimpDivTable, aes(x=YEAR, y=Geo.Evenness)) +
  geom_line(size=1, color="blue") + # Use hollow circles
  #ylab("Geographic Evenness") +
  xlab("Year")+
  ggtitle('(D) Geographic Evenness')+
  geom_point(color="black", shape=1)+
  # scale_y_continuous(breaks=seq(0, 1, 0.1))+
  scale_y_continuous(limits = c(0, 1))+
  scale_x_continuous(breaks=seq(1985, 2015, 5))
plotPOOLEDevenness<-plotPOOLEDevenness+theme_classic()+
  theme(axis.title.x=element_text(colour="black", size = 14, vjust=0),            #sets x axis title size, style, distance from axis #add , face = "bold" if you want bold
        #axis.title.y=element_text(colour="black", size = 14, vjust=2),            #sets y axis title size, style, distance from axis #add , face = "bold" if you want bold
        axis.title.y=element_blank(),
        axis.text=element_text(colour="black", size = 10),                              #sets size and style of labels on axes
        legend.title = element_blank(),   #Removes the Legend title
        legend.text = element_text(color="black", size=10),  
        legend.position = c(0.9,0.8),
        legend.background = element_rect(colour = 'black', size = 0.5, linetype='solid'),
        plot.margin =unit(c(1,1.5,1,1), "cm")) #+  #plot margin - top, right, bottom, left
plotPOOLEDevenness

######################################################
# Binding these up to make Fig. 1
######################################################
source("multiplot.R")
# if you jiust want to take a quick look at the results...
Fig1<-multiplot(jointRichnessPlot, plotPOOLEDsimpdiv, plotTOTALEDSvYear, plotPOOLEDevenness, cols=2)
# to save the figure in format for submission
# for an explanation of why you need to do multiplot INSIDe of ggsave see: http://stackoverflow.com/questions/11721401/r-save-multiplot-to-file
ggsave("Fig1.eps", plot = multiplot(jointRichnessPlot, plotPOOLEDsimpdiv, plotTOTALEDSvYear, plotPOOLEDevenness, cols=2), device = "eps", scale = 1, width = NA, height = NA, units = c("in", "cm", "mm"), dpi = 300, limitsize = TRUE)



##############################################################
# Fig 2A: bar chart of countries with the most unique editors  
##############################################################
cutoff = 9 # This is how many countries you want on the chart, all the rest will be in "OTHER"
editor.Geo<-arrange(Editor.Geo, desc(Pcnt_editors)) %>% select(geo.code,N_editors,Pcnt_editors)
most.common.editors<-slice(editor.Geo, 1:cutoff)
least.common.editors<-slice(editor.Geo, (cutoff+1):nrow(editor.Geo)) 
least.common.editors$geo.code<-"OTHER"
least.common.editors<-least.common.editors %>% 
  mutate(sum(N_editors)) %>%
  mutate(sum(Pcnt_editors)) %>% 
  select(-N_editors) %>% 
  select(-Pcnt_editors) %>% 
  rename(N_editors = `sum(N_editors)`) %>% 
  rename(Pcnt_editors = `sum(Pcnt_editors)`) %>% 
  slice(1:1)
most.common.editors<-bind_rows(most.common.editors, least.common.editors)
most.common.editors$geo.code<-as.factor(most.common.editors$geo.code)
most.common.editors

# This is needed to put them in order in the plot with OTHER at the end of the graph
order<-seq(1:nrow(most.common.editors))
most.common.editors$geo.code <- factor(most.common.editors$geo.code,most.common.editors$geo.code[levels = order])
# levels(most.common.editors$geo.code)
rm(order,editor.Geo,least.common.editors)

CountriesED<-arrange(most.common.editors) %>%  ggplot(aes(x=geo.code, y=Pcnt_editors)) +
  geom_bar(colour="black", stat="identity")+
  ylab("Percent") +
  xlab("Country")+
  ggtitle('(A) Editor Home Country')+
  scale_y_continuous(breaks=seq(0, 70, 5))
CountriesED<-CountriesED+theme_classic()+
  theme(axis.title.x=element_text(colour="black", size = 14, vjust=0),            #sets x axis title size, style, distance from axis #add , face = "bold" if you want bold
        axis.title.y=element_text(colour="black", size = 14, vjust=2),            #sets y axis title size, style, distance from axis #add , face = "bold" if you want bold
        axis.text=element_text(colour="black", size = 10),                              #sets size and style of labels on axes
        legend.title = element_blank(),   #Removes the Legend title
        legend.text = element_text(color="black", size=10),  
        legend.position = c(0.9,0.8),
        plot.margin=unit(c(1,1,2,1),"lines"),
        #aspect.ratio=1,
        legend.background = element_rect(colour = 'black', size = 0.5, linetype='solid'))
CountriesED


######################################################
# Fig 2B: Prop of the EDITOR POOL in EACH YEAR by REGION
# Note: thisis not "the average proportion of each editorial board". 
# This takes the list of people serving as editors in a year, makes sure
# that each person is listed only once (i.e., if an editor is on 2 boards in one
# year they are counted only once), and then calculates the proportion 
# of that pool from each Region
######################################################

RegionFig<-ggplot(data=RegionPlot, aes(x=YEAR, y=Percent, group=REGION, colour=REGION)) +
  geom_line(size=1)+
  ylab("Percent") +
  xlab("Year")+
  ggtitle('(B) Editor Region')+
  scale_y_continuous(limit = c(0, 100))+
  scale_x_continuous(breaks=seq(1984, 2014, 5))
RegionFig<-RegionFig+theme_classic()+
  theme(axis.title.x=element_text(colour="black", size = 14, vjust=0),            #sets x axis title size, style, distance from axis #add , face = "bold" if you want bold
        axis.title.y=element_text(colour="black", size = 14, vjust=2),            #sets y axis title size, style, distance from axis #add , face = "bold" if you want bold
        axis.text=element_text(colour="black", size = 10),                              #sets size and style of labels on axes
        legend.title = element_blank(),   #Removes the Legend title
        legend.text = element_text(color="black", size=10), 
        # legend.position = c(0.9,0.8),
        legend.position = "right",
        plot.margin=unit(c(1,1,2,1),"lines"),
        legend.background = element_rect(colour = 'black', size = 0.5, linetype='solid'))
#plot.margin =unit(c(0,1,0,1.5), "cm")) #+  #plot margin - top, right, bottom, left
RegionFig


######################################################
# Fig 2C: Prop of the EDITORS in EACH YEAR by COUNTRY INCOME
# Note: thisis not "the average proportion of each editorial board". 
# THis takes the list of people serving as editors in a year, makes sure
# that each person is listed only once (i.e., if an editor is on 2 boards in one
# year they are counted only once), and then calculates 
# the proportion of that pool from each country income category 
######################################################

IncomeFig<-ggplot(data=IncomePlot, aes(x=YEAR, y=Percent, group=INCOME_LEVEL, colour=INCOME_LEVEL)) +
  geom_line(size=1)+
  ylab("Percent") +
  xlab("Year")+
  ggtitle('(C) Editor National Income Category')+
  scale_y_continuous(limit = c(0, 100))+
  # scale_y_continuous(breaks=seq(0, 100, 10))+
  scale_x_continuous(breaks=seq(1984, 2014, 5))
IncomeFig<-IncomeFig+theme_classic()+
  theme(axis.title.x=element_text(colour="black", size = 14, vjust=0),            #sets x axis title size, style, distance from axis #add , face = "bold" if you want bold
        axis.title.y=element_text(colour="black", size = 14, vjust=2),            #sets y axis title size, style, distance from axis #add , face = "bold" if you want bold
        axis.text=element_text(colour="black", size = 10), 
        legend.title = element_blank(),   #Removes the Legend title
        legend.text = element_text(color="black", size=10), 
        # legend.position = c(0.9,0.8), 
        legend.position = "right",
        plot.margin=unit(c(1,1,2,1),"lines"),
        legend.background = element_rect(colour = 'black', size = 0.5, linetype='solid'))
#plot.margin =unit(c(0,1,0,1.5), "cm")) #+  #plot margin - top, right, bottom, left
IncomeFig


######################################################
# BINDING THESE UP TO MAKE FIGURE 2
######################################################
# uses source(muliplot.R) loaded at start of code
source("multiplot.R")
Fig2<-multiplot(CountriesED, RegionFig, IncomeFig, cols=1)
ggsave("Fig2.eps", plot = multiplot(CountriesED, RegionFig, IncomeFig, cols=1), device = "eps", scale = 1, width = NA, height = NA, units = c("in", "cm", "mm"), dpi = 300, limitsize = TRUE)

######################################################





######################################################
######################################################
#
# ANALYSES, TABLES, FIGURES: SUPPLEMENT
#
######################################################
######################################################

######################################################
#Table S1
######################################################

EdsFirstYr<-AnalysisData %>% 
  filter(YEAR == FirstYear) %>%  
  rbind(AnalysisData %>% filter(YEAR == 1987) %>% filter(JOURNAL%in% c("Conservation Biology" , "Functional Ecology", "Landscape Ecology"))) %>% 
  group_by(JOURNAL) %>%   #collect the data into groups by country
  summarize(EditorsFirstYr = n_distinct(editor_id)) %>% 
  arrange(JOURNAL)

CountriesFirstYr<-AnalysisData %>% 
  filter(YEAR == FirstYear) %>%  
  rbind(AnalysisData %>% filter(YEAR == 1987) %>% filter(JOURNAL%in% c("Conservation Biology" , "Functional Ecology", "Landscape Ecology"))) %>% 
  group_by(JOURNAL) %>%   #collect the data into groups by country
  summarize(CountriesFirstYr = n_distinct(geo.code)) %>% 
  arrange(JOURNAL)

EdsLastYr<-AnalysisData %>% 
  filter(YEAR == LastYear) %>% 
  group_by(JOURNAL) %>%   #collect the data into groups by country
  summarize(EditorsLastYr = n_distinct(editor_id))%>% 
  arrange(JOURNAL)

CountriesLastYr<-AnalysisData %>% 
  filter(YEAR == LastYear) %>%  
  group_by(JOURNAL) %>%   #collect the data into groups by country
  summarize(CountriesLastYr = n_distinct(geo.code)) %>% 
  arrange(JOURNAL)

EdsTotal<-AnalysisData %>% 
  group_by(JOURNAL) %>%   #collect the data into groups by country
  summarize(TotalEditors = n_distinct(editor_id)) %>% 
  arrange(JOURNAL)

CountriesTotal<-AnalysisData %>% 
  group_by(JOURNAL) %>%   #collect the data into groups by country
  summarize(TotalCountries = n_distinct(geo.code)) %>% 
  arrange(JOURNAL)

TABLE1<-full_join(EdsFirstYr,CountriesFirstYr, by = "JOURNAL")
TABLE1<-full_join(TABLE1,EdsLastYr, by = "JOURNAL")  
TABLE1<-full_join(TABLE1,CountriesLastYr, by = "JOURNAL") 
TABLE1<-full_join(TABLE1,EdsTotal, by = "JOURNAL") 
TABLE1<-full_join(TABLE1,CountriesTotal, by = "JOURNAL")
TABLE1<-mutate(TABLE1, CEratio=TotalEditors/TotalCountries)
TABLE1$Pcnt<-round(TABLE1$CEratio, digits=2)
TABLE1
rm(EdsFirstYr,CountriesFirstYr,EdsLastYr,CountriesLastYr,EdsTotal,CountriesTotal)
write.csv(TABLE1, file="/Users/emiliobruna/Dropbox/EMB - ACTIVE/MANUSCRIPTS/Editorial Board Geography/TableS1.csv", row.names = F) #export it as a csv file


######################################################
#chi-sq test: are there differences in frequency by region and income level?

Chi.region<-AnalysisData %>% group_by(REGION)  %>%  summarize(Editors=n_distinct(editor_id)) %>% mutate(Pcnt=Editors/sum(Editors)*100)  
chisq.test(Chi.region$Editors)

Chi.income<-AnalysisData %>% group_by(INCOME_LEVEL)  %>%  summarize(Editors=n_distinct(editor_id))%>% mutate(Pcnt=Editors/sum(Editors)*100)
chisq.test(Chi.income$Editors)



######################################################
######################################################
# GLS with Temp Autocorrleation
######################################################
######################################################
#Bind up the data for the analyses
GLS.data<-full_join(IsimpDivTable, EdsPerYr,by="YEAR")
GLS.data<-rename(GLS.data, Countries=AnnualRichness, Editors=TotalEditors) #Shorter
# Preliminary: is there evidence for Autocorrelation 
# GR: Yes
acf(GLS.data$Countries,lag.max=10) 
plot(acf(GLS.data$Countries,type="p")) #partial autocorrelation

# GD YES
acf(GLS.data$InvSimpson,lag.max=10) 
plot(acf(GLS.data$InvSimpson,type="p"))

# GE YES
acf(GLS.data$Geo.Evenness,lag.max=10) 
plot(acf(GLS.data$Geo.Evenness,type="p"))

# RESPONSE<-"Countries"
# RESPONSE<-"InvSimpson"
# RESPONSE<-"Geo.Evenness"

# library(nlme)
# https://stats.stackexchange.com/questions/13859/finding-overall-p-value-for-gls-model
# REML to test the utility of corARMA term
# TESTING THE EFFECT OF THE CORRELATION STRUCTURE
mAC1.1 <- gls(Countries ~ 1, data = GLS.data,  na.action = na.omit) 
mAC1.2 <- gls(Countries ~ 1, data = GLS.data, correlation = corARMA(p = 1), na.action = na.omit)
mAC2.1 <- gls(Countries ~ Editors, data = GLS.data,  na.action = na.omit) 
mAC2.2 <- gls(Countries ~ Editors, data = GLS.data, correlation = corARMA(p = 1), na.action = na.omit)
mAC3.1 <- gls(Countries ~ YEAR, data = GLS.data,  na.action = na.omit)
mAC3.2 <- gls(Countries ~ YEAR, data = GLS.data, correlation = corARMA(p = 1), na.action = na.omit)
mAC4.1 <- gls(Countries ~ Editors+YEAR, data = GLS.data, na.action = na.omit)
mAC4.2 <- gls(Countries ~ Editors+YEAR, data = GLS.data, correlation = corARMA(p = 1), na.action = na.omit)
mAC5.1 <- gls(Countries ~ Editors*YEAR, data = GLS.data, na.action = na.omit)
mAC5.2 <- gls(Countries ~ Editors*YEAR, data = GLS.data, correlation = corARMA(p = 1), na.action = na.omit)
# 
summary(mAC1.2)
model.sel(mAC1.1,mAC1.2,mAC2.1,mAC2.2,mAC3.1,mAC3.2,mAC4.1,mAC4.2,mAC5.1,mAC5.2)


# ML to test main effects
# Countries
# InvSimpson
# Geo.Evenness
m1.MAIN <- gls(Geo.Evenness ~ 1, data = GLS.data, correlation = corARMA(p = 1),na.action = na.omit,method = "ML")
m2.MAIN <- gls(Geo.Evenness ~ YEAR, data = GLS.data, correlation = corARMA(p = 1), na.action = na.omit,method = "ML")
m3.MAIN <- gls(Geo.Evenness ~ Editors,  data = GLS.data,correlation = corARMA(p = 1),na.action = na.omit,method = "ML")
m4.MAIN <- gls(Geo.Evenness ~ YEAR + Editors, data = GLS.data, correlation = corARMA(p = 1), na.action = na.omit,method = "ML")
m5.MAIN <- gls(Geo.Evenness ~ Editors*YEAR, data = GLS.data, correlation = corARMA(p = 1), na.action = na.omit,method = "ML")

summary(m1.MAIN)
summary(m2.MAIN)
summary(m3.MAIN)
summary(m4.MAIN)
summary(m5.MAIN)
# https://stats.stackexchange.com/questions/13859/finding-overall-p-value-for-gls-model
anova(m1.MAIN,m2.MAIN)
anova(m1.MAIN, m3.MAIN)
anova(m2.MAIN,m4.MAIN)
anova(m3.MAIN,m4.MAIN)
anova(m3.MAIN,m5.MAIN)
anova(m4.MAIN,m5.MAIN)
# library(MuMIn)
model.sel(m1.MAIN,m2.MAIN,m3.MAIN,m4.MAIN,m5.MAIN)



######################################################
# Supplement Fig S1: Countries in a Year vs. No of Editors in a Year (all journals pooled) 
######################################################

TotalEdsVGeo<-full_join(EdsPerYr,GEOperYR, by="YEAR")
plotTOTALedsVgeo<-ggplot(TotalEdsVGeo, aes(x=TotalEditors, y=AnnualRichness)) +
  ggtitle('(D) Geographic Richness')+
  # ylab("Geographic Richness") +
  xlab("Total No. of Editors")+
  # geom_line(size=1, color="blue")+
  geom_point(color="black", shape=1,size=1)+
  geom_smooth(method='lm', se=FALSE)+
  scale_y_continuous(breaks=seq(30, 60, 5))
plotTOTALedsVgeo<-plotTOTALedsVgeo+theme_classic()+
  theme(axis.title.x=element_text(colour="black", size = 14, vjust=0),            #sets x axis title size, style, distance from axis #add , face = "bold" if you want bold
        axis.title.y=element_text(colour="black", size = 14, vjust=2),            #sets y axis title size, style, distance from axis #add , face = "bold" if you want bold
        axis.text=element_text(colour="black", size = 10),                              #sets size and style of labels on axes
        legend.title = element_blank(),   #Removes the Legend title
        legend.text = element_text(color="black", size=10),  
        legend.position = c(0.9,0.8),
        legend.background = element_rect(colour = 'black', size = 0.5, linetype='solid'))
#plot.margin =unit(c(0,1,0,1.5), "cm")) #+  #plot margin - top, right, bottom, left
plotTOTALedsVgeo



######################################################
# Supplement Fig S2: Cumlative Editors vs Cumulative Authors
######################################################

AuthorCountries<-read.csv("./Data/AuthorCountries_1985_2014.csv", dec=".", header = TRUE, sep = ",", check.names=FALSE )
AuthorCountries<-AuthorCountries[AuthorCountries$YEAR>=FirstYear & AuthorCountries$YEAR<=LastYear,]
#if you want to see it looks ok...
AuthorCountries
#sum(AuthorCountries$N_Articles)

#add country codes and clean up
source("Country.Codes.R")
AuthorCountries<-Country.Codes(AuthorCountries)
levels(AuthorCountries$geo.code)


AuPerCountryPerYr.LONG<-AuthorCountries %>% group_by(YEAR, geo.code) %>% summarize(Total = n_distinct(geo.code))
# AuPerCountryPerYr.LONG[is.na(AuPerCountryPerYr.LONG)] <- 0

AuCumulative<-AuthorCountries %>% ungroup() %>%  select(-Pcnt_Pubs, COUNTRY) %>% group_by(YEAR,geo.code) %>% summarize(yr_tot=sum(N_Articles))
# AuCumulativem$YEAR<-as.numeric(AuCumulativem$YEAR)
AuCumulative<-spread(AuCumulative, geo.code,yr_tot)
AuCumulative[is.na(AuCumulative)] <- 0
AuCumulative<-as_tibble(AuCumulative)
AuCumulativePlot<-specaccum(AuCumulative, "collector")

AuCumulativePlot<-as.data.frame(AuCumulativePlot$richness)
AuCumulativePlot$richness<-as.vector(AuCumulativePlot$richness)
names(AuCumulativePlot)[1] <- "CumulativeRichness"
AuCumulativePlot$YEAR<-seq(1985,2014,1)

EDvAuCumRich<-full_join(AuCumulativePlot, editorAcum, by = "YEAR")
EDvAuCumRich <- EDvAuCumRich %>% select(YEAR, CumulativeRichness.x, CumulativeRichness.y) #reorder columns
EDvAuCumRich<-gather(EDvAuCumRich, "CumulativeRichness.x","CumulativeRichness.x", 2:3) 
EDvAuCumRich[EDvAuCumRich=="CumulativeRichness.x"]<-"Authors"
EDvAuCumRich[EDvAuCumRich=="CumulativeRichness.y"]<-"Editors"
names(EDvAuCumRich)[2] <- "Category"
names(EDvAuCumRich)[3] <- "N"
rm(AuPerCountryPerYr.LONG,AuthorCountries,AuCumulative,AuCumulativePlot)


#plot cumulative and annual richness same plot
EDvAuCumRichPlot<-ggplot(EDvAuCumRich, aes(x=YEAR, y=N, group = Category, colour = Category)) +
  geom_line(size=1) +
  scale_color_manual(values=c("blue", "red"))+
  geom_text(data = EDvAuCumRich[EDvAuCumRich$YEAR=="2012" & EDvAuCumRich$Category=="Editors",], aes(label = Category), hjust = 1, vjust = -1, size=5) +
  geom_text(data = EDvAuCumRich[EDvAuCumRich$YEAR=="2012" & EDvAuCumRich$Category=="Authors",], aes(label = Category), hjust = 1, vjust = -1, size=5) +
  ylab("Number of Countries") +
  xlab("Year")+
  ggtitle('Fig S2. Cumulative Geographic Richness from 1985-2014 of the editors for N = 24 environmental biology journals \n            and of the authors publishing in those journals during the same time perior (N = 113,816 articles).
          ')+
  geom_point(color="black", shape=1)+
  #scale_y_continuous(breaks = seq(20, 220,20))+
  scale_y_continuous(limits=c(1,max(EDvAuCumRich$N)+20))+
  scale_x_continuous(breaks=seq(1985, 2015, 5))

EDvAuCumRichPlot<-EDvAuCumRichPlot+theme_classic()+
  theme(axis.title.x=element_text(colour="black", size = 14, vjust=0),            #sets x axis title size, style, distance from axis #add , face = "bold" if you want bold
        axis.title.y=element_text(colour="black", size = 14, vjust=2),            #sets y axis title size, style, distance from axis #add , face = "bold" if you want bold
        axis.text=element_text(colour="black", size = 12),                              #sets size and style of labels on axes
        legend.title = element_blank(),   #Removes the Legend title
        legend.text = element_text(color="black", size=10),  
        # legend.position = c(0.9,0.8),
        legend.position = ("none"),
        legend.background = element_rect(colour = 'black', size = 0.5, linetype='solid'),
        plot.margin =unit(c(1,1.5,1,1), "cm")) #+  #plot margin - top, right, bottom, left
EDvAuCumRichPlot
ggsave("FigS2.eps", plot = EDvAuCumRichPlot, device = "eps", scale = 1, width = NA, height = NA, units = c("in", "cm", "mm"), dpi = 300, limitsize = TRUE)


######################################################
# Appendinx: Geo Richness of EDITORS EACH YEAR BY JOURNAL 
######################################################

# No. of editors on each journal's board in each year
EdsJrnlYr<-AnalysisData %>% group_by(JOURNAL, YEAR) %>% summarize(TotalEditors = n_distinct(editor_id))
# No. of countries on each journal's board in each year
CountriesJrnlYr<-AnalysisData %>% group_by(JOURNAL, YEAR) %>% summarize(TotalCountries = n_distinct(geo.code))
# bound into a single dataframe
JrnlData<-full_join(EdsJrnlYr,CountriesJrnlYr, by=c("JOURNAL", "YEAR"))
rm(EdsJrnlYr,CountriesJrnlYr)
JrnlData<-JrnlData %>% select(JOURNAL, YEAR,TotalCountries)

JrnlRichnessFig<-ggplot(data=JrnlData, aes(x=YEAR, y=TotalCountries)) +
  geom_line(size=1, color="blue")+
  facet_wrap(~JOURNAL, nrow=6)+
  ylab("Geographic Richness") +
  xlab("Year")+
  scale_y_continuous(breaks=seq(0, 30, 5))+
  scale_x_continuous(breaks=seq(1985, 2014, 5))
JrnlRichnessFig<-JrnlRichnessFig+theme_bw()+
  theme(panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        panel.spacing.y = unit(1, "lines"),
        # strip.background = element_rect(colour="black", fill="white"),
        panel.border = element_rect(colour = "black"),
        strip.text = element_text(face = "italic", size = 10))
JrnlRichnessFig

#plot.margin =unit(c(0,1,0,1.5), "cm")) #+  #plot margin - top, right, bottom, left



######################################################
# Appendix: Geo Diversity of EDITORS EACH YEAR split by JOURNAL
######################################################
EdsPerCountryPerJrnlPerYr.LONG<-AnalysisData %>% group_by(JOURNAL, YEAR, geo.code) %>% summarize(Total = n_distinct(editor_id))
EdsPerCountryPerJrnlPerYr.LONG[is.na(EdsPerCountryPerJrnlPerYr.LONG)] <- 0
DivDataJrnl<-as_tibble(EdsPerCountryPerJrnlPerYr.LONG)
DivDataJrnl<-spread(DivDataJrnl, geo.code, Total) 
DivDataJrnl[is.na(DivDataJrnl)] <- 0
DivDataJrnl<-ungroup(DivDataJrnl)
#Using simposns inverse
IsimpsonJRNL <- diversity((DivDataJrnl %>% select(-YEAR, - JOURNAL)), index="invsimpson") #Need to strip away the journal and year columns for vegan to do the analysis
# Table DIVERSITY with Results and Journals
JrnlIsimpDivTable <- data.frame(IsimpsonJRNL)
JrnlIsimpDivTable$YEAR <-DivDataJrnl$YEAR #Add year as a column
JrnlIsimpDivTable$JOURNAL <-DivDataJrnl$JOURNAL #Add year as a column
JrnlIsimpDivTable<-rename(JrnlIsimpDivTable, InvSimpson=IsimpsonJRNL) #rename the columns
JrnlIsimpDivTable <- JrnlIsimpDivTable[c("JOURNAL","YEAR","InvSimpson")] #reorder the columns
# ShannonDivTable<-arrange(ShannonDivTable, YEAR, desc(ShannonDiv)) # sort in descending order
JrnlIsimpDivTable

#computing evenness
GEOperYRJRNL<-EdsPerCountryPerJrnlPerYr.LONG %>% summarize(Countries = sum(n_distinct(geo.code)))
JrnlIsimpDivTable<-full_join(GEOperYRJRNL,JrnlIsimpDivTable, by=c("JOURNAL","YEAR"))
JrnlIsimpDivTable<-mutate(JrnlIsimpDivTable, Geo.Evenness = InvSimpson/Countries)

rm(GEOperYRJRNL, IsimpsonJRNL,DivDataJrnl,EdsPerCountryPerJrnlPerYr.LONG)


JrnlDiversityFig<-ggplot(data=JrnlIsimpDivTable, aes(x=YEAR, y=InvSimpson)) +
  geom_line(size=1, color="blue")+
  facet_wrap(~JOURNAL, nrow=6)+
  ylab("Geographic Diversity") +
  xlab("Year")+
  scale_y_continuous(breaks=seq(0, 18, 5))+   #####NEED TO SET MARGIN BY HIGHEST POSSIBLE VALUE FOR THAT JOURNAL???
  scale_x_continuous(breaks=seq(1985, 2014, 5))
JrnlDiversityFig<-JrnlDiversityFig+theme_bw()+
  theme(panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        panel.spacing.y = unit(1, "lines"),
        # strip.background = element_rect(colour="black", fill="white"),
        panel.border = element_rect(colour = "black"),
        strip.text = element_text(face = "italic", size = 10))
JrnlDiversityFig



######################################################
# Appendix: Geo Eveness of EDITORS EACH YEAR split by JOURNAL
######################################################

JrnlEvennessFig<-ggplot(data=JrnlIsimpDivTable, aes(x=YEAR, y=Geo.Evenness)) +
  geom_line(size=1, color="blue")+
  facet_wrap(~JOURNAL, nrow=6)+
  ylab("Geographic Evenness") +
  xlab("Year")+
  #scale_y_continuous(breaks=seq(0, 18, 5))+
  scale_x_continuous(breaks=seq(1985, 2014, 5))
JrnlEvennessFig<-JrnlEvennessFig+theme_bw()+
  theme(panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        panel.spacing.y = unit(1, "lines"),
        # strip.background = element_rect(colour="black", fill="white"),
        panel.border = element_rect(colour = "black"),
        strip.text = element_text(face = "italic", size = 10))
JrnlEvennessFig



######################################################
# Appendix: Prop of EDITORS EACH YEAR FROM EACH REGION  plit by JOURNAL
######################################################

RegionyrJRNL<-AnalysisData %>% group_by(JOURNAL, YEAR, REGION) %>% summarize(Total = n_distinct(editor_id))
RegionyrJRNL[is.na(RegionyrJRNL)] <- 0
RegionyrJRNL2<-RegionyrJRNL %>% group_by(JOURNAL, YEAR)  %>%  summarise(Editors=sum(Total))
RegionyrJRNL<-full_join(RegionyrJRNL,RegionyrJRNL2, by=c("JOURNAL","YEAR")) %>% mutate(pcnt=Total/Editors*100)
rm(RegionyrJRNL2)
RegionyrJRNLFig<-ggplot(data=RegionyrJRNL, aes(x=YEAR, y=pcnt, color=REGION)) +
  geom_line(size=1)+
  scale_x_continuous(breaks=seq(1985, 2014, 5))+
  facet_wrap(~JOURNAL, nrow=6, scales="free")+
  # facet_wrap(~JOURNAL, nrow=6, scales="free")+ #USE THIS ONE IF YOU USE NUMBERS INSTEAD OF % DUE TO UNEQUAL ED BOARD SIZES
  ylab("Editors from different global regions (%)") +
  xlab("Year")
RegionyrJRNLFig<-RegionyrJRNLFig+theme_bw()+
  theme(panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        panel.spacing.y = unit(1, "lines"),
        # strip.background = element_rect(colour="black", fill="white"),
        panel.border = element_rect(colour = "black"),
        strip.text = element_text(face = "italic", size = 10))
RegionyrJRNLFig

#plot.margin =unit(c(0,1,0,1.5), "cm")) #+  #plot margin - top, right, bottom, left




######################################################
# Appendix: Geo Prop of EDITORS EACH YEAR FROM EACH INCOME CATEGORY  plit by JOURNAL
######################################################

INCOMEyrJRNL<-AnalysisData %>% group_by(JOURNAL, YEAR, INCOME_LEVEL) %>% summarize(Total = n_distinct(editor_id))
INCOMEyrJRNL[is.na(INCOMEyrJRNL)] <- 0
INCOMEyrJRNL2<-INCOMEyrJRNL %>% group_by(JOURNAL, YEAR)  %>%  summarise(Editors=sum(Total))
INCOMEyrJRNL<-full_join(INCOMEyrJRNL,INCOMEyrJRNL2, by=c("JOURNAL","YEAR")) %>% mutate(pcnt=Total/Editors*100)
rm(INCOMEyrJRNL2)
INCOMErJRNLFig<-ggplot(data=INCOMEyrJRNL, aes(x=YEAR, y=pcnt, color=INCOME_LEVEL)) +
  geom_line(size=1)+
  scale_x_continuous(breaks=seq(1985, 2014, 5))+
  facet_wrap(~JOURNAL, nrow=6, scales="free")+
  # facet_wrap(~JOURNAL, nrow=6, scales="free")+ #USE THIS ONE IF YOU USE NUMBERS INSTEAD OF % DUE TO UNEQUAL ED BOARD SIZES
  ylab("Editors from countries in different income categories (%)") +
  xlab("Year")
INCOMErJRNLFig<-INCOMErJRNLFig+theme_bw()+
  theme(panel.grid.minor = element_blank(),
        strip.background = element_blank(),
        panel.spacing.y = unit(1, "lines"),
        # strip.background = element_rect(colour="black", fill="white"),
        panel.border = element_rect(colour = "black"),
        strip.text = element_text(face = "italic", size = 10))
INCOMErJRNLFig

#plot.margin =unit(c(0,1,0,1.5), "cm")) #+  #plot margin - top, right, bottom, left
